# Generated by Django 5.2.7 on 2025-11-01 19:09

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('Has_been_contacted', models.BooleanField(default=False)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_marks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_amategekoMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_KugendaMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_IbinyabizigaMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_IbimenyetsoMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_IbirangaMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_ImigenzurireMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('mastered_questions', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('last_quiz_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='rw', max_length=10, null=True)),
                ('taken', models.DateTimeField(auto_now_add=True, null=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('amategekoMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('KugendaMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('IbinyabizigaMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('IbimenyetsoMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('IbirangaMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ImigenzurireMarks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('from_state', models.CharField(blank=True, max_length=50, null=True)),
                ('to_state', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('access_code', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFG1234', length=6, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('ref_id', models.CharField(default='abc', max_length=120)),
                ('paying_number', models.CharField(max_length=12)),
                ('paid_on', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('exams', models.IntegerField(null=True)),
                ('expiration', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('failed', 'FAILED'), ('succeded', 'SUCCESS')], default='pending', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UssdUser',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='whatsapp_ussd.customer')),
                ('current_flow_state', models.CharField(db_index=True, default='welcome', max_length=50)),
                ('state_context', models.JSONField(blank=True, default=dict)),
                ('total_messages', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True, db_index=True)),
                ('preferred_language', models.CharField(default='rw', max_length=5)),
                ('failed_exams_count', models.IntegerField(default=0)),
                ('needs_coaching', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
            ],
            bases=('whatsapp_ussd.customer',),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='whatsapp_us_phone_n_ec68d3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['exam_date'], name='whatsapp_us_exam_da_d0b835_idx'),
        ),
        migrations.AddField(
            model_name='performance',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='whatsapp_ussd.customer'),
        ),
        migrations.AddField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_ussd.customer'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userevent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='whatsapp_ussd.customer'),
        ),
        migrations.AddIndex(
            model_name='userpayment',
            index=models.Index(fields=['paying_number'], name='whatsapp_us_paying__f7cf03_idx'),
        ),
        migrations.AddIndex(
            model_name='userpayment',
            index=models.Index(fields=['status'], name='whatsapp_us_status_9e629f_idx'),
        ),
        migrations.AddIndex(
            model_name='ussduser',
            index=models.Index(fields=['current_flow_state'], name='whatsapp_us_current_324fad_idx'),
        ),
        migrations.AddIndex(
            model_name='ussduser',
            index=models.Index(fields=['last_interaction'], name='whatsapp_us_last_in_5a0a71_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['customer', '-timestamp'], name='whatsapp_us_custome_e4eea4_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='whatsapp_us_event_t_2c664e_idx'),
        ),
    ]
