# Generated by Django 5.2.7 on 2025-11-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ussd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussduser',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
