# Generated by Django 5.2.7 on 2025-11-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_ussd', '0002_ussduser_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ussduser',
            name='history',
        ),
    ]
